# This workflow will do installation of node dependencies and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Testing before npm publish

on:
  push:
    branches: [ master ]
    paths:
      - '.github/workflows/testing.yml'
      - 'src/**'
      - 'test-suite/**'
      - 'pnpm-lock.yaml'

jobs:
  testing:
    name: Testing before npm publish

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - name: Use pnpm
      uses: pnpm/action-setup@v2
      with:
        version: 7
        run_install: false
    - run: pnpm install --frozen-lockfile
    - run: pnpm run test
